import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

const serviceFaqs = [
  {
    slug: "sewer-camera-inspection",
    faqs: [
      { q: "How much does a sewer camera inspection cost in London Ontario?", a: "Many companies in London charge $200 to $400 for a standalone sewer camera inspection. At Discount Drain, we include a free video camera inspection with every service call, so you pay nothing extra to see exactly what is happening in your pipe." },
      { q: "How long does a sewer camera inspection take?", a: "Most residential inspections take 30 to 60 minutes from start to finish. The camera is fed through the cleanout access point and travels the full length of the accessible pipe. You watch the footage live on a monitor as we go." },
      { q: "What can a sewer camera inspection find?", a: "The camera can identify root intrusion, cracks and fractures in the pipe wall, collapsed or partially collapsed sections, offset joints where pipe sections have shifted, bellied pipe (sections that have sagged and hold standing water), grease and scale buildup, and foreign objects lodged in the line." },
      { q: "Do I need a sewer camera inspection before buying a house in Ontario?", a: "A standard home inspection does not include the sewer line. In older London neighbourhoods where clay tile pipes are common, a camera inspection before closing is one of the most useful things you can do. If the camera finds root intrusion or a cracked pipe, you have room to negotiate or ask the seller to address it before you sign." },
      { q: "Where is the cleanout access point for a sewer camera inspection?", a: "The cleanout is usually in the basement, the utility room, or outside near the foundation. If your home does not have an accessible cleanout, we can access the line through a roof vent or by removing a toilet. We will find the right access point before starting." },
      { q: "Will the camera inspection tell me if the problem is on city property?", a: "Yes. The camera travels the full length of the private sewer line from your house to the connection point. If the main issue is in the city's portion of the pipe (the Private Drain Connection), we will identify that clearly. The City of London has a flat-rate PDC renewal program at $7,250 as of 2026, payable over 10 years through your property taxes." },
      { q: "Can a sewer camera inspection be done on any type of pipe?", a: "Yes. The camera works in clay tile, cast iron, PVC, ABS, and concrete pipe. The diameter of the pipe determines which camera head we use. Most residential sewer lines in London range from 4 to 6 inches in diameter." },
      { q: "What happens after the inspection if a problem is found?", a: "We explain what we found, show you the footage, and walk through your options. Depending on the issue, that might be a cleaning, a pipe lining, a spot repair, or in more serious cases, excavation and replacement. You get the information first and make the decision from there." },
      { q: "Can tree roots really damage a sewer line?", a: "Yes, and it is the most common finding in older London homes. Roots enter through small cracks or joint gaps in clay tile pipes and grow over time. They can partially or fully block the line. If roots are found, we will tell you whether cleaning is sufficient or whether lining the pipe makes more sense to prevent the roots from returning." },
      { q: "How often should I have a sewer camera inspection done?", a: "If you have an older clay tile sewer line and mature trees near the line, every two to three years is a reasonable schedule. If you have already had root intrusion, annual inspection is worth considering. For newer PVC lines with no history of problems, inspection at the time of purchase and then as needed is typically sufficient." },
      { q: "Is a sewer camera inspection covered by home insurance in Ontario?", a: "The inspection itself is not typically covered by insurance. However, if the inspection reveals damage that qualifies under your policy's sewer backup or water damage coverage, the repair work may be covered. Check your policy or call your broker before assuming coverage either way." },
      { q: "What is the difference between a sewer camera inspection and a drain scope?", a: "They are the same thing described differently. A sewer camera inspection, drain scope, sewer scope, and CCTV inspection all refer to the process of running a camera through the pipe to view its condition. The terms are used interchangeably in the industry." },
      { q: "Can I get a recording of the inspection footage?", a: "Yes. We can provide footage from the inspection so you have a record of the pipe condition. This is particularly useful for home buyers who want documentation to share with a real estate agent or insurance broker." },
    ]
  },
  {
    slug: "trenchless-pipe-repair",
    faqs: [
      { q: "What is trenchless pipe repair and how does it work?", a: "Trenchless pipe repair replaces or rehabilitates a damaged underground pipe without digging a trench along its length. The two main methods are pipe lining (CIPP), where a resin-coated liner is inserted and cured inside the existing pipe to form a new one, and pipe bursting, where a head is pulled through the old pipe to break it outward while pulling new pipe in behind it. Both methods require only small access points at each end." },
      { q: "Is trenchless pipe repair available in London Ontario?", a: "Yes. Discount Drain has been performing trenchless repairs in London and Southwestern Ontario for years. We use CIPP lining and pipe bursting depending on the condition of the pipe and the specific situation." },
      { q: "How much does trenchless pipe repair cost in Ontario?", a: "For a typical residential sewer line in London, pipe lining generally runs between $4,000 and $8,000 depending on the length, depth, and condition of the pipe. This is significantly less than traditional excavation, which can run $10,000 to $20,000 or more once driveway restoration is included. A camera inspection is needed to give you an accurate quote." },
      { q: "Is trenchless repair as durable as replacing the pipe?", a: "Yes. A properly installed CIPP liner creates a seamless pipe inside the existing one, with no joints for roots to enter. The liner material is rated for 50 years or more under normal conditions. In many cases, the lined pipe outperforms a new clay tile or cast iron pipe because the smooth interior improves flow." },
      { q: "Can trenchless repair be done under a driveway or landscaping?", a: "That is one of the main advantages. Because no trench is needed, the driveway, garden, patio, or lawn above the pipe is left completely undisturbed. This is why trenchless repair often costs less overall even if the per-foot cost of the liner is similar to new pipe, because there is no restoration work afterward." },
      { q: "What pipe materials can be repaired with trenchless methods?", a: "CIPP lining works in clay tile, cast iron, concrete, and PVC pipe. Pipe bursting is typically used for clay tile and cast iron. The condition and diameter of the existing pipe determines which method is appropriate. A camera inspection will show us what we are working with." },
      { q: "How long does trenchless pipe repair take?", a: "Most residential trenchless repairs are completed in a single day. The liner curing process takes a few hours depending on the method used (heat or UV). You will typically have your drains back in service by the end of the day." },
      { q: "Can trenchless repair fix root intrusion?", a: "Yes. If roots have entered the pipe through cracks or joint gaps, lining the pipe seals those entry points permanently. The liner creates a smooth, continuous surface with no joints, which eliminates the gaps that roots exploit. Roots already inside the pipe are cleared before the liner is installed." },
      { q: "What happens if the pipe is too damaged for trenchless repair?", a: "If the pipe has collapsed completely or the structural damage is too severe for lining to adhere properly, pipe bursting may still be an option. If neither trenchless method is viable, we will tell you honestly and explain what excavation would involve. We do not push trenchless repair when it is not the right solution." },
      { q: "Does trenchless repair require a permit in Ontario?", a: "Permit requirements vary by municipality. In London, some sewer repair work requires a permit from the city. We handle the permit process as part of the job so you do not have to navigate that on your own." },
      { q: "Will trenchless repair fix a bellied pipe?", a: "A bellied pipe is a section that has sagged and holds standing water. Lining a bellied pipe does not fix the sag, but it can seal cracks and prevent further deterioration. In some cases, the belly is minor enough that lining is still worthwhile. In others, excavation to correct the grade is the better option. The camera footage will show us the severity." },
      { q: "Is trenchless pipe repair covered by home insurance in Ontario?", a: "Some Ontario home insurance policies include sewer backup or water damage coverage that may apply to sewer line repair. Coverage varies significantly by policy and insurer. We recommend calling your broker before the repair to understand what is covered. We can work with your insurance company directly if needed." },
      { q: "How do I know if my pipe is a candidate for trenchless repair?", a: "A camera inspection is the only way to know for certain. The camera shows us the condition of the pipe, the location and type of damage, and whether the pipe has enough structural integrity to support a liner. We will give you a clear answer after the inspection." },
    ]
  },
  {
    slug: "wet-basement-waterproofing",
    faqs: [
      { q: "Why does my basement get wet in spring in Ontario?", a: "Spring is the most common time for wet basements in Ontario because snowmelt raises the water table and saturates the soil around the foundation. If your weeping tile system is aging or partially blocked, it cannot handle the volume of water, and moisture finds its way through the foundation wall or floor. Freeze-thaw cycles through the winter can also open up small cracks in the foundation." },
      { q: "What is weeping tile and why does it fail?", a: "Weeping tile is the drainage system installed around the perimeter of your foundation when the house was built. In older London homes, it is often clay tile or early perforated pipe that has been in the ground for 40 to 60 years. Over time it can crack, collapse, or become clogged with silt and roots. When it fails, groundwater accumulates against the foundation instead of draining away." },
      { q: "How much does basement waterproofing cost in London Ontario?", a: "Interior weeping tile replacement with a sump pump typically runs between $3,000 and $12,000 depending on the size of the basement and the extent of the work. Exterior waterproofing, which involves excavating around the foundation, costs more but addresses the problem at the source. The right solution depends on where the water is coming from, which we determine through a proper assessment." },
      { q: "What is the difference between interior and exterior waterproofing?", a: "Interior waterproofing installs a drainage system inside the basement to collect water that gets through the foundation and direct it to a sump pump. It does not stop water from entering the wall, but it manages it before it causes damage. Exterior waterproofing excavates around the foundation, applies a waterproof membrane to the outside of the wall, and replaces the weeping tile. It stops water at the source but costs more and involves significant excavation." },
      { q: "Does Discount Drain offer a warranty on basement waterproofing?", a: "Yes. Our wet basement repair work comes with a 20-year warranty. We stand behind the work we do." },
      { q: "What is a backwater valve and do I need one?", a: "A backwater valve is a device installed in your main sewer line that allows water to flow out but prevents sewage from flowing back in during heavy rainfall events when the city sewer system gets overloaded. If your basement has flooded with sewage during a heavy rain, a backwater valve is worth considering. The City of London has offered rebate programs for backwater valve installation in the past. Check the current city website for available programs." },
      { q: "How do I know if my wet basement is a drainage problem or a foundation crack?", a: "A simple test: tape a piece of plastic sheeting to the wet wall and seal all four edges. Leave it for 24 to 48 hours. If moisture appears on the room side of the plastic, it is condensation from humid air. If it appears on the wall side, water is coming through from outside. The location of the wet spot also gives clues. Water at the base of the wall where it meets the floor usually points to a drainage issue. Water partway up the wall often indicates a crack or porous concrete." },
      { q: "Can a wet basement be fixed without excavating the yard?", a: "In many cases, yes. Interior weeping tile installation and sump pump systems can manage groundwater effectively without any exterior excavation. Whether interior waterproofing is sufficient depends on the source and severity of the water intrusion. We will assess the situation and tell you honestly what is needed." },
      { q: "What is a sump pump and do I need one?", a: "A sump pump sits in a pit at the lowest point of the basement and pumps water out of the house when the pit fills. If you have a weeping tile system, it drains into the sump pit. A sump pump is a standard component of most interior waterproofing systems. Battery backup sump pumps are worth considering in Ontario because power outages often happen during the heavy rainstorms that cause basement flooding." },
      { q: "Will basement waterproofing affect my home's resale value?", a: "A dry basement with a documented waterproofing system and warranty is a selling point. A wet basement is a red flag for buyers and can significantly affect the sale price or kill a deal entirely. Addressing a wet basement before listing is generally worth the investment." },
      { q: "Is wet basement repair covered by home insurance in Ontario?", a: "Standard home insurance policies in Ontario typically do not cover gradual water seepage or drainage failures. Sudden sewer backup may be covered if you have sewer backup coverage on your policy. Overland flooding coverage is a separate add-on that some insurers offer. Check your policy carefully and call your broker before assuming coverage." },
      { q: "How long does basement waterproofing take?", a: "Interior weeping tile installation in a typical London home basement takes one to three days depending on the size of the space and the extent of the work. Exterior waterproofing takes longer because of the excavation involved. We will give you a clear timeline before starting." },
      { q: "What causes white powder or staining on basement walls?", a: "That white powdery residue is called efflorescence. It is mineral salt left behind when water moves through concrete and evaporates. It is a sign that water is moving through the wall, even if the wall does not feel wet. Efflorescence by itself is not structural damage, but it is an indicator that moisture is present and worth addressing." },
    ]
  },
  {
    slug: "drain-cleaning",
    faqs: [
      { q: "How much does drain cleaning cost in London Ontario?", a: "A standard drain snaking for a single drain typically runs $150 to $300 in the London area. Main line cleaning with a power flusher is generally $300 to $500. Emergency or after-hours calls cost more. Prices vary by company and by the complexity of the job. If you have been quoted significantly more than this for a straightforward cleaning, it is worth getting a second opinion." },
      { q: "What is the difference between snaking a drain and power flushing?", a: "A drain snake (also called an auger) is a flexible cable that is fed into the pipe to break up or retrieve a clog. It is effective for clogs close to the drain opening. Power flushing (also called hydro jetting) uses high-pressure water to scour the inside of the pipe, removing grease, scale, and debris along the full length of the line. Power flushing is more thorough and is the better choice for main line maintenance." },
      { q: "Why are multiple drains in my house slow at the same time?", a: "When a single drain is slow, the problem is usually local. When multiple drains in different rooms are slow at the same time, the blockage is further down in the main sewer line where everything connects. This is a main line issue and needs to be addressed at that level, not by snaking individual drains." },
      { q: "Can I use chemical drain cleaners instead of calling a plumber?", a: "Chemical drain cleaners can clear a minor clog, but they are hard on pipes, particularly older metal pipes, and they do nothing for root intrusion or structural problems. If the drain is slow and the chemical cleaner does not fix it within a day or two, the problem is likely not a simple grease buildup. Repeated use of chemical cleaners can also damage pipe joints over time." },
      { q: "How often should I have my drains cleaned?", a: "Kitchen drains benefit from cleaning once a year for most households. Bathroom drains typically need cleaning every one to two years. The main sewer line in an older London home with clay tile pipe and mature trees nearby should be inspected and cleaned every two to three years. If roots have been found before, annual cleaning or pipe lining is worth considering." },
      { q: "What causes kitchen drains to get slow?", a: "Grease and food particles are the main culprits. Even if you run hot water when pouring grease down the drain, the grease cools and solidifies further down the pipe. Over time, the buildup narrows the pipe opening until water drains slowly. Dish soap and food scraps add to the buildup. The fix is a proper cleaning, not just hot water." },
      { q: "What causes bathroom drains to get slow?", a: "Hair is the primary cause in bathroom drains. It catches on the inside of the pipe and traps soap scum, creating a blockage that builds gradually. A drain strainer helps reduce the amount of hair entering the pipe, but it does not eliminate the problem entirely. Bathroom drains generally need less frequent cleaning than kitchen drains." },
      { q: "Can tree roots get into drain pipes?", a: "Yes, and it is very common in older London neighbourhoods. Roots enter through small cracks or joint gaps in clay tile pipes and grow over time. A drain cleaning can clear roots temporarily, but they tend to grow back. If roots are found repeatedly, lining the pipe is usually the more cost-effective long-term solution." },
      { q: "What is a drain cleanout and do I have one?", a: "A cleanout is an access point in the drain or sewer line that allows a plumber to insert a snake or camera without removing a toilet or opening a wall. It is usually a capped pipe in the basement, utility room, or outside near the foundation. Many older London homes have cleanouts, but not all. If yours does not, one can be added during a service call." },
      { q: "Why does my drain smell even after cleaning?", a: "A clean drain should not smell. If the odour persists after cleaning, the source may be a dry P-trap (the curved pipe under the sink that holds water to block sewer gas), a cracked pipe that is allowing sewer gas to escape, or buildup further down the line that the cleaning did not reach. A camera inspection can identify the source." },
      { q: "Is drain cleaning covered by home insurance in Ontario?", a: "Routine drain cleaning is a maintenance cost and is not covered by home insurance. If a blocked drain causes water damage to your home, the damage may be covered depending on your policy. Sewer backup coverage is a separate add-on that some Ontario insurers offer. Check your policy or call your broker." },
      { q: "How long does a drain cleaning take?", a: "A single drain cleaning typically takes 30 to 60 minutes. Main line cleaning takes longer, usually one to two hours, depending on the length of the line and the severity of the buildup. We will give you a time estimate when we arrive." },
      { q: "What should I do if my drain is completely blocked and water is backing up?", a: "Stop using water in the house to avoid making the backup worse. Call us at 519-451-8342. We are available 24 hours a day, 7 days a week for emergencies. Do not use chemical drain cleaners if the drain is completely blocked, as the chemicals will sit in the pipe and can cause damage." },
    ]
  },
  {
    slug: "sewer-repair-installation",
    faqs: [
      { q: "How much does sewer line repair cost in London Ontario?", a: "Costs vary significantly depending on the method used and the extent of the damage. Trenchless pipe lining for a typical residential line runs $4,000 to $8,000. Full excavation and replacement can run $10,000 to $20,000 or more once driveway restoration is included. A camera inspection is the only way to give you an accurate number for your specific situation." },
      { q: "How do I know if my sewer line needs to be repaired or replaced?", a: "A sewer camera inspection is the definitive answer. Signs that suggest a problem include multiple slow drains, gurgling toilets, sewage smell inside the house, sewage backing up into the basement floor drain, and soggy patches in the yard. The camera shows us exactly what is happening and where, so we can recommend the right solution." },
      { q: "What type of sewer pipe is in my older London Ontario home?", a: "Most homes built before the 1980s in London have clay tile sewer lines. Clay tile was the standard material for decades and can last a long time, but it is susceptible to root intrusion, cracking from ground movement, and joint separation over time. Homes built in the 1980s and later typically have PVC or ABS pipe, which is more resistant to roots and corrosion." },
      { q: "Who is responsible for the sewer line from my house to the street?", a: "The sewer line has two sections. The private section from your house to the property line is your responsibility. The Private Drain Connection (PDC) from the property line to the city main is also technically your responsibility to maintain, but the City of London offers a flat-rate PDC renewal program. As of 2026, the fee is $7,250 and can be paid over 10 years through your property taxes. A camera inspection can determine which section has the problem." },
      { q: "Can the city be responsible for any part of my sewer repair?", a: "The City of London's PDC renewal program covers the section of the line from your property line to the city main at a flat rate of $7,250 as of 2026. This can be added to your property taxes over 10 years. If the camera shows the main problem is in the city's portion of the line, this program is worth knowing about before agreeing to private repair work." },
      { q: "What is the difference between sewer repair and sewer replacement?", a: "Repair addresses specific damaged sections of the pipe, either through trenchless lining, spot excavation and patching, or pipe bursting. Replacement involves removing and replacing the entire line, usually through full excavation. The right approach depends on the extent and location of the damage. We will recommend the most cost-effective solution after the camera inspection." },
      { q: "How long does sewer line repair take?", a: "Trenchless repairs are typically completed in a single day. Excavation and replacement takes longer, usually two to five days depending on the length of the line, the depth, and the surface restoration required. We will give you a clear timeline before starting." },
      { q: "Will sewer repair require a permit in London Ontario?", a: "Yes, most sewer repair work in London requires a permit from the city. We handle the permit process as part of the job." },
      { q: "Can sewer repair be done in winter in Ontario?", a: "Yes, though frozen ground can complicate excavation work. Trenchless repairs are generally not affected by cold weather. If you have an emergency in winter, call us and we will assess what is possible given the conditions." },
      { q: "What happens to my yard or driveway during sewer repair?", a: "With trenchless methods, the surface above the pipe is left undisturbed. With excavation, the area above the trench needs to be restored after the pipe is repaired. We restore the surface as part of the job, though concrete driveways may require a separate concrete contractor depending on the scope." },
      { q: "Is sewer line repair covered by home insurance in Ontario?", a: "Some Ontario home insurance policies include sewer backup or water damage coverage that may apply to sewer line repair. Coverage varies significantly by policy and insurer. We recommend calling your broker before the repair to understand what is covered. We can work with your insurance company directly if needed." },
      { q: "What is a sewer liner and how long does it last?", a: "A sewer liner (CIPP) is a resin-coated tube that is inserted into the existing pipe and cured in place to form a new pipe inside the old one. A properly installed liner is rated for 50 years or more. It creates a seamless, smooth interior with no joints for roots to enter, which often improves flow compared to the original pipe." },
      { q: "Can I get a second opinion on a sewer repair quote?", a: "Absolutely. If you have been quoted for sewer repair and want a second assessment, call us at 519-451-8342. We include a free camera inspection with every service call, so you will see exactly what we see and can compare assessments directly." },
    ]
  },
  {
    slug: "excavation-services",
    faqs: [
      { q: "What types of excavation services does Discount Drain offer?", a: "We handle deep excavations for sewer and drain line repair and replacement, parking lot preparation, pool installation, grading, and general site work. Our fleet includes three excavators and two dump trucks, so we can handle residential and commercial projects of varying scale." },
      { q: "When is excavation necessary for sewer repair?", a: "Excavation is needed when the pipe has completely collapsed, when the damage is too extensive for trenchless repair, when the pipe needs to be replaced rather than lined, or when the grade of the pipe needs to be corrected. A camera inspection determines whether trenchless methods are viable before we recommend excavation." },
      { q: "How much does excavation cost in London Ontario?", a: "Excavation costs depend on the depth, length, soil conditions, and what needs to be restored afterward. A residential sewer line excavation in London typically runs from $8,000 to $20,000 or more depending on these factors. Driveway restoration, if required, adds to the total. We provide a detailed quote after assessing the site." },
      { q: "Will excavation damage my driveway or landscaping?", a: "Excavation does disturb the surface above the trench. We restore the surface as part of the job. Concrete driveways may require a separate concrete contractor depending on the scope. We will be clear about what restoration is included in the quote before starting." },
      { q: "How long does an excavation project take?", a: "A typical residential sewer line excavation and replacement takes two to five days depending on the length of the line, the depth, soil conditions, and the surface restoration required. Larger commercial or municipal projects take longer. We will give you a clear timeline before starting." },
      { q: "Do you handle excavation for pool installation in Ontario?", a: "Yes. We handle the excavation phase of pool installation projects. If you are planning a pool in London or Southwestern Ontario, contact us to discuss the scope and timeline." },
      { q: "Can you excavate in tight or restricted spaces?", a: "Yes. We have equipment sized for different access situations, including compact excavators for areas with limited clearance. We assess the site before quoting to make sure we have the right equipment for the job." },
      { q: "Do you handle soil removal and disposal?", a: "Yes. Our dump trucks handle soil removal and disposal as part of excavation projects. We will confirm what is included in the quote." },
      { q: "Is a permit required for excavation work in London Ontario?", a: "Most excavation work involving underground utilities or sewer lines requires a permit from the City of London. We handle the permit process as part of the job. We also contact Ontario One Call (Call Before You Dig) to locate underground utilities before any excavation begins." },
      { q: "What is Ontario One Call and why does it matter for excavation?", a: "Ontario One Call is the province's utility locating service. Before any excavation, contractors are legally required to contact Ontario One Call to have underground utilities (gas, hydro, water, telecom) marked. We handle this as a standard part of every excavation project." },
      { q: "Can you do excavation work for commercial properties?", a: "Yes. We handle commercial excavation projects including parking lot preparation, catch basin installation, sewer and drain line work, and site grading. Contact us to discuss the scope of your project." },
      { q: "What happens if unexpected underground utilities or conditions are found during excavation?", a: "We stop work immediately, assess the situation, and contact the relevant utility company if needed. We will communicate clearly with you about what was found and what it means for the project timeline and cost before proceeding." },
      { q: "Do you offer free quotes for excavation projects?", a: "Yes. Contact us at 519-451-8342 to arrange a site visit and quote. Excavation projects require an on-site assessment to give you an accurate number." },
    ]
  },
];

for (const service of serviceFaqs) {
  const faqsJson = JSON.stringify(service.faqs);
  await conn.execute(
    `UPDATE services SET faqs = ? WHERE slug = ?`,
    [faqsJson, service.slug]
  );
  console.log(`Updated FAQs for: ${service.slug} (${service.faqs.length} FAQs)`);
}

await conn.end();
console.log("All service FAQs updated.");
